# image will be published to ghcr.io/<user>/<name>
name: ec-silverblue-nvidia-20240109
# description will be included in the image's metadata
description: This is my personal Silverblue Nvidia image from template specified in the name.

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/silverblue-nvidia
# image-version: 38 # latest is also supported if you want new updates ASAP
# latest is still updating to 38
# image-version: latest
# see https://github.com/ublue-os/nvidia/pkgs/container/silverblue-nvidia/versions for versions available
image-version: 39

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      - usr: /usr
          # copy static configurations
          #
          # copies config/files/usr into your image's /usr
          #
          # configuration you wish to end up in /etc/ on the booted system
          # should be added into /usr/etc/ as that is the proper "distro"
          # config directory on ostree. Read more in the files module's README

  - type: rpm-ostree
    repos:
      - https://copr.fedorainfracloud.org/coprs/alternateved/bleeding-emacs/repo/fedora-%OS_VERSION%/alternateved-bleeding-emacs-fedora-%OS_VERSION%.repo
      - https://copr.fedorainfracloud.org/coprs/atim/lazygit/repo/fedora-%OS_VERSION%/atim-lazygit-fedora-%OS_VERSION%.repo
      - https://copr.fedorainfracloud.org/coprs/atim/lazygit/repo/fedora-%OS_VERSION%/atim-nushell-fedora-%OS_VERSION%.repo
      - https://copr.fedorainfracloud.org/coprs/atim/starship/repo/fedora-%OS_VERSION%/atim-starship-fedora-%OS_VERSION%.repo
      - https://copr.fedorainfracloud.org/coprs/flekz/helix-git/repo/fedora-%OS_VERSION%/flekz-helix-git-fedora-%OS_VERSION%.repo
      - https://copr.fedorainfracloud.org/coprs/g/sway-sig/sway-desktop/repo/fedora-%OS_VERSION%/group_sway-sig-sway-desktop-fedora-%OS_VERSION%.repo
      - https://copr.fedorainfracloud.org/coprs/nucleo/gocryptfs/repo/fedora-%OS_VERSION%/nucleo-gocryptfs-fedora-%OS_VERSION%.repo
      - https://copr.fedorainfracloud.org/coprs/peterwu/iosevka/repo/fedora-%OS_VERSION%/peterwu-iosevka-fedora-%OS_VERSION%.repo
      - https://copr.fedorainfracloud.org/coprs/solopasha/hyprland/repo/fedora-%OS_VERSION%/solopasha-hyprland-fedora-%OS_VERSION%.repo
      - https://copr.fedorainfracloud.org/coprs/varlad/zellij/repo/fedora-%OS_VERSION%/varlad-zellij-fedora-%OS_VERSION%.repo
      - https://copr.fedorainfracloud.org/coprs/wezfurlong/wezterm-nightly/repo/fedora-%OS_VERSION%/wezfurlong-wezterm-nightly-fedora-%OS_VERSION%.repo
      - https://terra.fyralabs.com/terra.repo
      - https://gist.github.com/ecocode/f910ca1621ba29220074bc281e6b8a78/raw/daa76873e8a38e16b0575b9c8099324667cb7dcf/insync.repo
      - https://fbreader.org/linux/rpms/fbreader.repo
    install:
      - atool
      - appimagelauncher
      - bat
      - bemenu
      - bettercap
      - cargo
      - cryfs
      - distrobox
      - dconf-editor
      - egl-wayland
      - entr
      - eza
      - fbreader
      - fd-find
      - firewall-config
      - fish
      - foot
      - foot-terminfo
      - fzf
      - glances
      - glibc-locale-source
      - gnome-tweaks
      - gocryptfs
      - grim
      - hotspot
      - imv
      - insync
      - intel-media-driver
      - inxi
      - j4-dmenu-desktop
      - jrnl
      - kanshi
      - kitty
      - kitty-terminfo
      - light
      - lm_sensors
      - lshw
      - lynx
      - macchanger
      - mako
      - mediainfo
      - mpv
      - network-manager-applet
      - NetworkManager-tui
      - nnn
      # - nushell - installed from scripts/cargo.sh
      # - nvidia-vaapi-driver
      - nvtop
      - odt2txt
      - openh264
      - openssl-devel
      - pasystray
      - perf
      - perl-File-MimeInfo
      - plasma-wayland-protocols
      - pulseaudio-utils
      - qt6-qtwayland
      - ripgrep
      - river
      - rofi-wayland
      - samba
      - slurp
      - sshfs
      - starship
      - strace
      - sway
      # - swayr - installed from scripts/cargo.sh
      - swayidle
      - swaylock
      - taskopen
      - tilix
      - tmux
      - trash-cli
      - variety
      - virt-install
      - virt-manager
      - virt-top
      - virt-viewer
      - waybar
      # - wayfire
      - webkit2gtk4.0
      - wdisplays
      - wezterm
      - wl-clipboard
      - wofi
      - xdg-desktop-portal-wlr
      - xorg-x11-drv-nvidia-cuda
    remove:
      - firefox # default firefox removed in favor of flatpak
      - firefox-langpacks # langpacks needs to also be removed to prevent dependency problems

  - type: bling # configure what to pull in from ublue-os/bling
    install:
      - justfiles
        # add "!include /usr/share/ublue-os/just/bling.just"
        # in your custom.just (added by default) or local justfile
      - nix-installer # shell shortcuts for determinate system's nix installers
      - ublue-os-wallpapers
      # - ublue-update # https://github.com/ublue-os/ublue-update
      # - 1password # install 1Password (stable) and `op` CLI tool
      # - dconf-update-service # a service unit that updates the dconf db on boot
      # - devpod # https://devpod.sh/ as an rpm
      # - gnome-vrr # enables gnome-vrr for your image
      # - container-tools # installs container-related tools onto /usr/bin: kind, kubectx, docker-compose and kubens
      # - laptop # installs TLP and configures your system for laptop usage
      # - flatpaksync # allows synchronization of user-installed flatpaks, see separate documentation section


  - type: yafti
      # if included, yafti and it's dependencies (pip & libadwaita)
      #  will be installed and set up
    custom-flatpaks:
      # this section is optional
      # - Celluloid: io.github.celluloid_player.Celluloid
      # - Krita: org.kde.krita

  - type: script
    scripts:
      # this sets up the proper policy & signing files for signed images to work
      - signing.sh
      - cargo.sh
